Feature/deck fix
gisat-panther/ptr-maps pull request #126
Opened 2022-05-11 11:22 UTC by vdubr

2022-05-12 07:24 UTC, vlach1989 commented
IMHO, it should be minor version

2022-05-12 08:00 UTC, vlach1989 requested changes

2022-05-13 10:14 UTC, vdubr commented
> IMHO, it should be minor version

Changed to minor

2022-05-13 17:43 UTC, vlach1989 approved these changes

2022-05-16 07:10 UTC, merged